import type { Metadata } from "next";
import "./styles/global.scss";
import "bootstrap-icons/font/bootstrap-icons.css";
import ClientProviders from "./context/react-query/ClientProviders";

export const metadata: Metadata = {
  title: "Worklink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

      <ClientProviders>
          {children}
      </ClientProviders>

      </body>
    </html>
  );
}
